# Generated by Django 4.2.9 on 2024-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtubelink',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
